services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - checkout_pg:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d checkout"]
      interval: 5s
      timeout: 5s
      retries: 30

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - checkout_rabbit:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  checkout-be:
    image: eclipse-temurin:25-jdk-alpine
    working_dir: /app
    environment:
      JAR_FILE: checkout-0.0.1-SNAPSHOT.jar
      JAVA_TOOL_OPTIONS: >-
        -Duser.timezone=UTC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/checkout
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8010:8080"
      - "5010:5005"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./target:/app/target:ro
    command: ["sh", "-c", "java -jar /app/target/$$JAR_FILE"]
    develop:
      watch:
        - action: restart
          path: ./target/${JAR_FILE}
          target: /app/target/${JAR_FILE}

volumes:
  checkout_pg:
  checkout_rabbit:
